finalLaunch/finalLaunch/urls.py
from django.conf.urls import include, url,static
from django.conf import settings
from django.contrib import admin
from homePage.views import homeView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','homePage.views.homeView',name='homeView'),
    url(r'^register/$','homePage.views.ajaxHomeView',name='ajaxHomeView'),
    url(r'^legal-disrupt/$','blogHome.views.ldHomeView',name='ldHomeView'),
    url(r'^legal-disrupt/articles/(?P<slug>[^\.]+)/$','blogHome.views.singleArticleView',name='singleArticleView'),
    url(r'^lawyer-registration/$','registerLawyer.views.lawyerRegisterView',name='lawyerRegisterView'),
    url(r'^thank-you/$','registerLawyer.views.lawyerThankView',name='lawyerThankView'),
    url(r'^legal-disrupt/articles/$','blogHome.views.allArticleView',name='allArticleView'),

]+ static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404='blogHome.views.handler404'

 

finalLaunch/registerLawyer/models.py
from datetime import datetime
from django.db import models

# Create your models here.
class LawyerRegisterDetail(models.Model):
	GENDER_CHOICES=(('Male','Male'),('Female','Female'),)
	first_name=models.CharField(max_length=100)
	last_name=models.CharField(max_length=100)
	city_name=models.CharField(max_length=100)
	company_name=models.CharField(max_length=200,blank=True)
	date_of_birth=models.DateField()
	gender=models.CharField(choices=GENDER_CHOICES,default=GENDER_CHOICES[0][0],max_length=6)
	email=models.EmailField()
	phone_number=models.CharField(max_length=20)
	state_bar_no=models.CharField(blank=True,max_length=50)
	bar_council_no=models.CharField(blank=True,max_length=50)
	#terms_conditions=models.BooleanField(default=False)
	register_time=models.DateTimeField(default=datetime.now,blank=True)
	def __str__(self):
		return self.email + " registered at " +self.register_time.strftime("%Y-%m-%d")

finalLaunch/registerLawyer/forms.py
from django import forms
from django.forms import extras
from .models import LawyerRegisterDetail
GENDER_CHOICES=(('Male','Male'),('Female','Female'),)
class lawyerRegisterForm(forms.ModelForm):
	gender=forms.ChoiceField(choices=GENDER_CHOICES,initial=GENDER_CHOICES[0][0], widget=forms.RadioSelect())
	#date_of_birth= forms.DateField(widget=)
	#date_of_birth=forms.DateField(widget=forms.DateInput())
	class Meta:
		model = LawyerRegisterDetail
		fields='__all__'
		widgets={
			'first_name':forms.TextInput(
					attrs={'placeholder':'First name','type':'text','class':'form-control'}
				),
			'last_name':forms.TextInput(
					attrs={'placeholder':'Last name','type':'text','class':'form-control'}
				),
			'city_name':forms.TextInput(
					attrs={'placeholder':'Choose your city','type':'text','class':'form-control'}
				),
			'company_name':forms.TextInput(
					attrs={'placeholder':'Enter company name','type':'text','class':'form-control'}
				),
			'date_of_birth':extras.SelectDateWidget(
					attrs={'class':'form-control date-picker'},years=range(1905,2016)
				),
			'email':forms.EmailInput(
					attrs={'placeholder':'Enter your email address','type':'email','class':'form-control'}
				),
			'phone_number':forms.NumberInput(
					attrs={'placeholder':'Enter your 10-digit mobile number','type':'number','class':'form-control'}
				),
			'state_bar_no':forms.TextInput(
					attrs={'placeholder':'State Bar where you originally enrolled','type':'text','class':'form-control'}
				),
			'bar_council_no':forms.TextInput(
					attrs={'placeholder':'Bar Council number','type':'text','class':'form-control'}
				)
			

		}
		exclude=['register_time']

finalLaunch/registerLawyer/views.py
from django.shortcuts import render
from .forms import  lawyerRegisterForm
from .models import LawyerRegisterDetail

# Create your views here.
def lawyerRegisterView(request):
	if request.method=='POST':
		reg_form=lawyerRegisterForm(request.POST)
		if reg_form.is_valid():
			print("xxxxxxxxxxxxxxxxxxxxxx")

			reg_obj=reg_form.save()
			reg_obj.save()
			return render(request,'registerLawyer/registerThankyou.html',{'reg_obj':reg_obj})
		
		else:
			print(reg_form.errors)
			
	if request.method=='GET':
		reg_form=lawyerRegisterForm()
	return render(request,'registerLawyer/registerBlock.html',{'reg_form':reg_form})

def lawyerThankView(request):
	if request.method=='GET':
		return render(request,'registerLawyer/registerThankyou.html')

finalLaunch/registerLawyer/templates/registerLawyer/registerBase.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  	<meta charset="UTF-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<!--  	<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin">-->
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'registerLawyer/css/registerLawyer.css' %}">
</head>
<body>
<header>
	<div class="container">
		<img id="lawyered-logo" src="{% static 'registerLawyer/images/logo.png' %}" height="50" width="155">
	</div>
</header>
{% block registerLawyer %}
{% endblock %}
{% block thankYou %}
{% endblock %}



<section id="connect-us">
		<div class="container">
			<div class="connect-heading">
				<h4>CONNECT WITH US</h4>
				<div class="small-line"></div>
			</div>
			<div class="row footer-stuff">
				<div class="col-sm-4 col-md-4 footer-nav">
					<p>Give us a call!</p>
					<p>call @<span class="p-span">+91-9898989898</span></p>
				</div>
				<div class="col-sm-4 footer-nav">
					<p>Have a question?</p>
					<p>Email us @<span class="p-span">info@lawyered.in</span></p>
				</div>
				<div class="col-sm-4 footer-nav">
					<p>We are social @</p>
					<p>
						<span><img src=""></span>
						<span><img src=""></span>
						<span><img src=""></span>
						<span><img src=""></span>
					</p>
				</div>
			</div>		
		</div>	
	</section>


</body>
</html>

finalLaunch/registerLawyer/templates/registerLawyer/registerBlock.html
{% extends "registerLawyer/registerBase.html" %}
{% load staticfiles %}
{% block registerLawyer %}
	<section id="thrilled-us">
		<p>We are thrilled that you'd like to apply for early registration for <span>LAWYERED</span>
			please fill out the form below and submit us your details!
		</p>
		
	</section>


  <section id="form-section">
	<div class="container all-form-stuff">
		<h5><strong>Fill in your details and register:</strong></h5>
		<form id="register-form" action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="cover-box">
		      <p class="input2 first">
				<label class="input-labels"for="id_first_name">NAME *</label><br>
				{{reg_form.first_name}}<br><br>
				<span class="errors">{{reg_form.first_name.errors.as_text}}<span>
			  </p>
			  <p class="input2 second" >	
				<label class="input-labels"  for="id_last_name"></label><br>
				{{reg_form.last_name}}<br>
				<span class="errors">{{reg_form.last_name.errors.as_text}}</span>
			  </p>
			</div>
			<div class="cover-box">
		      <p class="input2 first">
				<label class="input-labels" for="id_city_name">CITY *</label><br>
				{{reg_form.city_name}}<br>
				<span class="errors">{{reg_form.city_name.errors.as_text}}</span>
			  </p>
			  <p class="input2 second">	
				<label class="input-labels" for="id_company_name">COMPANY</label><br>
				{{reg_form.company_name}}<br>
				<span class="errors">{{reg_form.company_name.errors.as_text}}
			  </p>
			</div>
			<div class="cover-box">
		      <p class="input2 first">
				<label class="input-labels" for="id_date_of_birth">DATE OF BIRTH *</label><br>
				<span class="date-of-b"> {{reg_form.date_of_birth}}
				</span><br>
				<span class="errors">{{reg_form.date_of_birth.errors.as_text}}</span>
			  </p>
			  <p class="input2 second">	
				<label class="input-labels" for="id_gender">GENDER</label><br>
				{{reg_form.gender}}<br>
				<span class="errors">{{reg_form.gender.errors.as_text}}</span>
			  </p>
			</div>
			<div class="cover-box">
		      <p class="input2 first">
				<label class="input-labels" for="id_email">E-MAIL*</label><br>
				{{reg_form.email}}<br>
				<span class="errors">{{reg_form.email.errors.as_text}}</span>
			  </p>
			  <p class="input2 second">
				<label class="input-labels" for="id_phone_number">PHONE NUMBER*</label><br>
				{{reg_form.phone_number}}<br>
				<span class="errors">{{reg_form.phone_number.errors.as_text}}</span>
			  </p>
			</div>
			<div class="cover-box">
		      <p class="input2 first">
				<label class="input-labels" for="id_state_bar_no">STATE BAR</label><br>
				{{reg_form.state_bar_no}}<br>
				<span class="errors">{{reg_form.state_bar_no.errors.as_text}}</span>
			  </p>
			  <p class="input2 second">	
				<label class="input-labels" for="id_bar_council_no">BAR COUNCIL NUMBER</label><br>
				{{reg_form.bar_council_no}}<br>
				<span class="errors">{{reg_form.bar_council_no.errors.as_text}}</span>
			  </p>
			</div>
			<div class="big-line"></div>
			<p class="mandatory-fields">* Mandatory fields</p>
			<input class="btn btn-default" id="button2" type="submit" value="submit">
		</form>
	</div>	
</section>
<script type="text/javascript" src="{% static 'jquery/jquery-2.1.3.js' %}"></script>

{% endblock %}

finalLaunch/registerLawyer/templates/registerLawyer/registerThankyou.html
{% extends "registerLawyer/registerBase.html" %}
{% load staticfiles %}
{% block thankYou %}
	<section id="thank-you">
	<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.lawyered.in" data-text="Hello All" data-size="large">Tweet
  </a>

		<h3>
T           HANK YOU FOR REGISTERING WITH US!
		</h3>
		<p>our customer relation manager will contact you soon</p>
	</section>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
  </script>

{% endblock %}